deployment/src/main.cpp

- Add precision inference in libtorch
- Add visualization tools

Add half precision inference in libtorch

---

.github/workflows/stable.yml
models/backbone.py
models/box_head.py
models/yolo.py
test/test_engine.py
test/test_models.py
test/test_torchscript.py

Refactor model unittest

---

notebooks/export-relay-inference-tvm.ipynb

Add TVM deployment tutorials

---

notebooks/export-relay-inference-tvm.ipynb

A follow-up PR of #50, its format is flawed.

Fix TVM tutorial format

---

.github/workflows/ci_test.yml
README.md
hubconf.py
test/test_utils.py
yolort/models/__init__.py
yolort/models/backbone_utils.py
yolort/models/common.py
yolort/models/darknet.py
yolort/models/experimental.py
yolort/models/path_aggregation_network.py
yolort/models/yolo.py
yolort/utils/__init__.py
yolort/utils/update_module_state.py
yolort/utils/updated_checkpoint.py

Support ultralytics released v4.0 stacks

---

hubconf.py
notebooks/export-onnx-inference-onnxruntime.ipynb
notebooks/export-relay-inference-tvm.ipynb
test/test_onnx.py
yolort/models/__init__.py
yolort/utils/activations.py

Add export friendly substitutions of SiLU

---

README.md

Add instructions of minimial PyTorch version

---

yolort/models/transform.py

Follow the upstream https://github.com/pytorch/vision/pull/3654

Unify onnx and JIT resize implementations

---

deployment/README.md
deployment/src/main.cpp

Closes #134 , To resolve the libtorch version conflicts.

Update C++ interfaces of TorchVision to 0.9.0+

---

tools/eval_metric.py
yolort/utils/logger.py

Adding time logging in eval_metric.py to make the printing look better.

Add time logging in eval_metric.py

---

README.md

Add @itsnine as co-authors for great contributions on ONNX Runtime.

Add Fidan as co-authors for great contributions on ORT

---

deployment/tensorrt/README.md
deployment/tensorrt/main.cpp

似乎一切正常...
Set 0.4 as the `score_thresh`.

Complete TRT example!

---

docs/source/models.rst
yolort/models/yolov5.py

Try to fix the docs in `yolort.models`

Fix docs and add docstrings for `YOLOv5`

---

yolort/runtime/openvino_helper.py

Add OpenVINO conversion and inference helpers

Init OpenVINO conversion utilities

---

yolort/data/coco_eval.py
yolort/data/data_module.py

This is a follow-up PR of #355

Fix lightning import for building docs

---

.github/workflows/ci-test.yml
.github/workflows/codeql-analysis.yml

Bump codeql-action and codecov-action

---

yolort/runtime/openvino_helper.py
yolort/runtime/y_openvino.py

This reverts commit 228b5861dc5e6539c7a9d7c88bbd977d94a6c170.

Revert "Remove openvino support temporarily (#362)"

---

README.md

Thanks @triple-Mu for his long great support for yolort project.
Highly PR so far
- #293
- #334
- #336
- #409

Add Song Lin as co-authors

---

tools/export_model.py
yolort/relay/__init__.py
yolort/relay/head_helper.py
yolort/runtime/ort_helper.py

This is a follow-up PR of #413 
```sh
python tools/export_model.py --checkpoint_path yolov5s.pt --vanilla
```
cc @triple-Mu

Refactor `FakeYOLO` and `VanillaONNXBuilder`

---

yolort/utils/visualizer.py

Compatibility fixes for numpy 1.23

---

yolort/data/coco.py
yolort/data/coco_eval.py
yolort/data/data_module.py
yolort/relay/ir_visualizer.py
yolort/relay/trt_graphsurgeon.py
yolort/runtime/trt_helper.py
yolort/runtime/y_onnxruntime.py
yolort/runtime/y_tensorrt.py
yolort/utils/__init__.py
yolort/utils/image_utils.py
yolort/utils/logger.py
yolort/utils/visualizer.py
yolort/v5/models/yolo.py
yolort/v5/utils/augmentations.py
yolort/v5/utils/general.py
yolort/v5/utils/plots.py
yolort/v5/utils/torch_utils.py

Compatibility fixes for Windows systems

---

deployment/tensorrt-yolov6/README.md

https://mp.weixin.qq.com/s/oxWodmYtULp5KznSYI19wQ

Add TensorRT YOLOv6 tutorial with graphics

---

deployment/tensorrt-yolov6/main.cpp

Fix `BGR2RGB` in preprocessing

---

yolort/relay/trt_graphsurgeon.py

Specify the onnx outputs shape exported for tensorrt

Specify the ONNX outputs shape for TensorRT

---

yolort/runtime/y_tensorrt.py

read image to gpu ,  the inferencing time reduced by 0.5ms

Perform pre-processing on GPU for TensorRT

---

yolort/v5/models/common.py

> Is the Focus layer equivalent to a simple Conv layer?
Another interpretation for https://github.com/ultralytics/yolov5/issues/4825#issue-998038464

Add fully convolutional `Focus2`

---

yolort/v5/models/yolo.py

Make compatible with yolov5 6.2 release

---

yolort/models/yolov5.py
yolort/runtime/y_tensorrt.py

Support image with 4-channel PNG format

Set RGB mode in read_image
