models/anchor_utils.py
torchscript support `torch.dtype` now, refer to https://github.com/pytorch/vision/pull/3032
=> Correcting incorrect types

datasets/__init__.py, datasets/coco.py, datasets/coco_eval.py, datasets/transforms.py, datasets/voc.py, datasets/voc_eval.py, engine.py, main.py, models/_utils.py, models/box_head.py, models/yolo.py, utils/misc.py
Just add some essential scripts for supporting training. Hope for next follow-up PR to support training coco and voc datasets.
=> Add essential scripts for training

README.md, detect.py, hubconf.py, notebooks/export-onnx-inference-onnxruntime.ipynb, notebooks/inference-pytorch-export-libtorch.ipynb, notebooks/visualize-jit-models.ipynb, requirements.txt
=> Update default parameters

.github/workflows/nightly.yml
There are something wrong of `onnx` and `onnxruntime` unittest in nightly version, refer to https://github.com/pytorch/vision/issues/3007
=> Enable unittest in pytorch nightly version

.github/workflows/nightly.yml, .github/workflows/stable.yml, requirements.txt, test/tracing/test_tracing.cpp
This is updated with libtorch restructuring from https://github.com/pytorch/vision/pull/3146 and onnxruntime unstream updating from https://github.com/pytorch/vision/pull/3160 .
=> Fix ops missing from upstream

test/test_models.py, yolort/models/box_head.py, yolort/models/yolo.py
Revert  https://github.com/zhiqwang/yolov5-rt-stack/commit/fa3c15695492ea73f00c6579ab1c4f8d86ce7840, fix part of #60 .
=> Initialize bias into YoloHead

test/test_models.py, test/test_onnx.py, test/test_torchscript.py, yolort/models/__init__.py, yolort/models/backbone_utils.py, yolort/models/experimental.py, yolort/models/yolo.py, yolort/models/yolotr.py
The model structure and trained checkpoint is copy-paste from <https://github.com/ultralytics/yolov5/pull/2333> .
=> Apply Transformer to YOLO

test/test_data_pipeline.py, test/test_engine.py, test/test_torchscript.py, yolort/models/box_head.py, yolort/models/yolo.py, yolort/models/yolo_module.py, yolort/utils/__init__.py, yolort/utils/file_utils.py
=> Support training with vanilla module

test/common_utils.py, yolort/data/_helper.py, yolort/models/experimental.py, yolort/utils/image_utils.py
=> Replaced print() with logger #94

requirements.txt
Following the upstream YOLOv5: https://github.com/ultralytics/yolov5/pull/2604#issue-601032324
> Cython should be a dependency of the remaining packages in requirements.txt, so should be installed anyway even if not a direct requirement.
=> Add comments about requirements

yolort/models/transform.py
`targets` was missing a default value of `None` making using YOLOTransform on its own require explicitly passing `None` during inference.
=> Made targets argument in YOLOTransform.forward() truly optional.

yolort/models/anchor_utils.py
AnchorGenerator.grid_anchors had fp32 hard-coded which could result in forward pass returning mismatched datatypes, for example (fp32, fp16, fp16).
Fix for #107
=> AnchorGenerator will use dtype of input feature_maps

notebooks/how-to-align-with-ultralytics-yolov5.ipynb, yolort/models/yolo.py
Closes #119. I tested it only with yolov5_darknet_pan_s_r40 a.k.a. yolov5s from ultralytics.
=> Support autoenvolved anchors from ultralytics

yolort/models/anchor_utils.py
torch.arange cannot export to onnx with fp16 precision so it is necessary to force the operation into fp32 and then cast the result to the desired dtype.
=> AnchorGenerator forces torch.arange in fp32 to allow export to onnx

yolort/models/transform.py
=> Fixing normalization in dataloader

test/common_utils.py, test/test_data_pipeline.py, test/test_onnx.py, yolort/data/data_module.py, yolort/models/yolo_module.py, yolort/train.py
=> Fixing trainer with lightning

README.md, deployment/libtorch/main.cpp
=> Attach libtorch inference results

deployment/libtorch/main.cpp
I know I didn't open an issue before creating these changes, so feel free to discuss here in the PR. 
Let me know your thoughts or if you'd like anything done differently!
=> Added more descriptive error logging

test/test_engine.py, tools/eval_metric.py, tools/train_net.py, yolort/data/coco_eval.py, yolort/models/yolo.py
For `yolov5`, run following script:
```bash
CUDA_VISIBLE_DEVICES=1 python tools/eval_metric.py \
--num_gpus 1 \
--image_path ./data-bin/mscoco/coco2017/val2017/ \
--annotation_path ./data-bin/mscoco/coco2017/annotations/instances_val2017.json
```
The expected results of `yolort.models.yolov5s`:
```
The evaluated mAP 0.5:095 is 32.311, and mAP 0.5 is 51.168.
```
_**Note**: Because we are using different dataloder in `yolort` to make yolov5 `torch.jit.scriptable`, so the mAP is not equal to `ultralytics/yolov5`, checkout #92 for more details._
For `torchvision`, run following script:
```bash
CUDA_VISIBLE_DEVICES=1 python tools/eval_metric.py \
--num_gpus 1 \
--num_classes 91 \
--batch_size 4 \
--arch fasterrcnn_resnet50_fpn \
--eval_type torchvision \
--image_path …
```
=> Add coco metrics evaluation CLI

yolort/models/anchor_utils.py
Following the upstream https://github.com/pytorch/vision/pull/4409 .
cc @dkloving . I remember that you also encountered some issues here when you did the `fp16` conversion before, so if this modification affects your subsequent use, please don't mind letting me know.
=> Change dtype from torch.float32 to torch.int32 in anchor_utils.py

notebooks/export-onnx-inference-onnxruntime.ipynb
As mentioned in https://github.com/zhiqwang/yolov5-rt-stack/pull/171#issuecomment-925482780, we should use the dynamic output shape when exporting the ONNX models.
=> Fix dynamic shape when exporting ONNX

deployment/onnxruntime-python/README.md, deployment/onnxruntime-python/example.py
@zhiqwang hi, I'm already done with this feature, could you check it? Temporary I did onnxruntime-python folder, but you could restructure folders as you want.
Let me know if you have any issues.
Resolve #177
=> Add ONNXRuntime python inference.

.gitignore, README.md, test/test_models.py, yolort/models/__init__.py, yolort/models/yolo.py, yolort/models/yolo_module.py, yolort/utils/update_module_state.py, yolort/v5/helper.py
Adopt `classmethod` to call `load_from_yolov5` in `YOLOv5`.
=> Refactor `load_from_yolov5` in `YOLOv5`

deployment/onnxruntime/README.md
The `ONNX` model exported with `yolort` differs from the official one in the following three ways.
- The exported `ONNX` graph now supports dynamic shapes, and we use `(3, H, W)` as the input shape (for example `(3, 640, 640)`).
- We embed the pre-processing ([`letterbox`](https://github.com/ultralytics/yolov5/blob/9ef94940aa5e9618e7e804f0758f9a6cebfc63a9/utils/augmentations.py#L88-L118)) into the graph as well. We only require the input image to be in the `RGB` channel, and to be rescaled to `float32 [0-1]` from general `uint [0-255]`. The main logic we use to implement this mechanism is below. (And [this](https://github.com/zhiqwang/yolov5-rt-stack/blob/b9c67205a61fa0e9d7e6696372c133ea0d36d9db/yolort/models/transform.py#L210-L234) plays the same role of the official `letterbox`, but …
=> Add notes about the exported ONNX model

deployment/onnxruntime/CMakeLists.txt, deployment/onnxruntime/README.md, deployment/onnxruntime/main.cpp, tools/export_model.py
=> Fix the type bug in labels

yolort/models/darknetv4.py, yolort/models/path_aggregation_network.py
Close #234 
I think the optimization of the `SPP` module should be done in the downstream framework, and we should keep the parts of PyTorch simple, so let's revert the `SPPF` to `SPP`.
=> Revert `SPPF` to `SPP`

test/test_relaying.py, test/test_runtime.py, yolort/models/box_head.py, yolort/relaying/__init__.py, yolort/runtime/__init__.py, yolort/runtime/yolo_tensorrt_model.py
This is a follow-up PR of #238 to make the exported ONNX model can be worked on TensorRT.
```python
import torch
from torch import Tensor
from yolort.runtime import YOLOTRTModule
from yolort.v5 import attempt_download
model_path = "yolov5n.pt"
checkpoint_path = attempt_download(model_path)
model = YOLOTRTModule(checkpoint_path, score_thresh=score_thresh)
model.eval()
samples = torch.rand(1, 3, 320, 320)
outs = model(samples)
assert isinstance(outs[0], dict)
assert isinstance(outs[0]["boxes"], Tensor)
assert isinstance(outs[0]["scores"], Tensor)
model.to_onnx("yolov5n.onnx")
```
=> Remove low scoring filter from LogitsDecoder

tools/export_model.py
Use the following to set the image size of the ONNX model:
```bash
python export_model.py --checkpoint_path [path/to/your/model.pt] --image_size 320 320
```
=> Set argument `image_size` configurable in export_model.py

tools/detect.py, yolort/models/box_head.py, yolort/runtime/__init__.py, yolort/runtime/trt_helper.py, yolort/runtime/y_tensorrt.py, yolort/runtime/yolo_tensorrt_model.py, yolort/utils/image_utils.py, yolort/v5/utils/datasets.py, yolort/v5/utils/general.py
Add the TensorRT Python CLI for yolort:
```bash
python tools/detect.py --weights yolov5.engine
--source ./test/assets/bus.jpg
--img_size 320 320
--conf_thres 0.35
```
=> Add TensorRT Python interface and CLI

test/test_runtime.py, tools/detect.py, yolort/models/box_head.py, yolort/runtime/__init__.py, yolort/runtime/trt_helper.py, yolort/runtime/y_tensorrt.py, yolort/runtime/yolo_graphsurgeon.py, yolort/runtime/yolo_tensorrt_model.py
Register the `BatchedNMS_TRT` plugin node at the end of `YOLOTRTModule`, and now we can get an end-to-end ONNX graph except the pre-processing.
```python
import torch
from yolort.runtime import PredictorTRT
engine_path = 'yolov5s.engine'
device = torch.device("cuda")
engine = PredictorTRT(engine_path, device)
img_path = 'bus.jpg'
image = cv2.imread(img_path)
image = engine.preprocessing(image)
detections = engine.run_on_image(image)
```
=> Fix register_nms in `YOLOGraphSurgeon`

yolort/models/box_head.py, yolort/runtime/trt_helper.py, yolort/runtime/y_tensorrt.py
- Fix example in `PredictorTRT`
- Fix docstrings for `PredictorTRT`
- Move `LogitsDecoder` into trt_helper.py
=> Move `LogitsDecoder` into trt_helper.py and fix docstrings

README.md, deployment/tensorrt/README.md
- Add Shiquan as co-authors for great contributions on TRT
- Update README in deployment/tensorrt
- Update TensorRT statement
- Update badges
=> Add Shiquan as co-authors for great contributions on TRT

tools/detect.py
I have delete useless params and add some code about changing image size list as two element list.
=> Remove expired parameters in detect.py

test/test_models.py, yolort/models/_utils.py, yolort/models/anchor_utils.py, yolort/models/box_head.py, yolort/models/yolo.py, yolort/runtime/trt_helper.py
An example to export the torchscript for the checkpoint trained with ultralytics/yolov5:
```python
import cv2
import torch
from yolort.models import YOLO
from yolort.utils import read_image_to_tensor
from yolort.v5 import letterbox, attempt_download
img_path = "test/assets/zidane.jpg"
img_raw = cv2.imread(img_path)
img = letterbox(img_raw, new_shape=(640, 640))[0]
img = read_image_to_tensor(img)
checkpoint_path = attempt_download("yolov5n6.pt")
model = YOLO.load_from_yolov5(checkpoint_path, score_thresh=0.25)
model.eval()
scripted_model = torch.jit.script(model)
scripted_model.eval()
x = img[None]
out = model(x)
out_script = scripted_model(x)
torch.testing.assert_close(out[0]["scores"], out_script[1][0]["scores"], rtol=0, atol=0)
torch.testing.assert_close(out[0]["labels"], …
```
=> Fix TorchScript exporting for custom checkpoints

test/test_runtime.py
- Rename to `test_yolo_trt_module_to_onnx`
- Add unittest for `test_yolo_graphsurgeon_wo_nms`
- Add unittest for `test_yolo_graphsurgeon_register_nms`
=> Add unittests for YOLOGraphSurgeon

deployment/libtorch/README.md, deployment/libtorch/main.cpp, deployment/tensorrt/README.md, notebooks/export-relay-inference-tvm.ipynb, notebooks/how-to-align-with-ultralytics-yolov5.ipynb, notebooks/inference-pytorch-export-libtorch.ipynb, notebooks/onnx-graphsurgeon-inference-tensorrt.ipynb, test/test_onnx.py, tools/export_model.py, yolort/models/backbone_utils.py, yolort/relaying/trace_wrapper.py, yolort/runtime/trt_helper.py, yolort/runtime/yolo_graphsurgeon.py, yolort/utils/image_utils.py
Feel free to edit further if you'd like. Not sure if `test_ouputs`, `num_clases`, and  `bboxs_list` were purposely done.
=> Fixed some spelling/typos

yolort/data/transforms.py
Ported from https://github.com/pytorch/vision/pull/5278
We found a bug on the original implementation of `RandomZoomOut` from TorchVision, so I thought to patch this copy as well. The good news is that we plan soon to move these transforms in TorchVision main library (using the new Transforms API) so you won't have to maintain them in your repo. But until then, this will do.
=> Fix a bug and document RandomZoomOut

.github/workflows/ci-test.yml
- Install yolort in GH Actions
- Upgrade torch to 1.10.2 from 1.10.1
=> Install yolort in GH Actions

yolort/data/coco_eval.py, yolort/data/transforms.py
Follow the upstream https://github.com/pytorch/vision/pull/4452 .
=> Replaced to_tensor() with pil_to_tensor() + convert_image_dtype()

notebooks/comparison-between-yolort-vs-yolov5.ipynb, test/test_models_transform.py, test/test_onnx.py, yolort/models/transform.py, yolort/models/yolo_module.py
- Rename `auto_shape` to `fixed_shape` in `YOLOTransform`
- Support `fixed_shape` method for pre-processing
=> Support fixed shape inference in pre-processing

deployment/libtorch/README.md, deployment/libtorch/main.cpp
- Compatible with Windows environment
- ~Use LibTorchVision to read images in the LibTorch demo~
We've met issues about the LibTorchVision
```
libc++abi: terminating with uncaught exception of type c10::Error: decode_jpeg: torchvision not compiled with libjpeg support
Exception raised from decode_jpeg at /tmp/torchvision-20220127-98534-apsyj/vision-0.11.3/torchvision/csrc/io/image/cpu/decode_jpeg.cpp:10 (most recent call first):
frame #0: c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*) + 92 (0x10452b0d8 in libc10.dylib)
frame #1: vision::image::decode_png(at::Tensor const&, long long) + 0 (0x1046be46c in libtorchvision.dylib)
frame #2: ReadImage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 72 (0x10425a574 …
```
=> Compatible with Windows for LibTorch deployment

deployment/tensorrt/main.cpp
Image after letterbox:
result:
=> Add letterbox for TRT inference

deployment/onnxruntime/README.md, notebooks/export-onnx-inference-onnxruntime.ipynb, test/test_runtime_ort.py, tools/export_model.py, yolort/models/yolov5.py, yolort/runtime/ort_helper.py
We introduce a new tool to export ONNX models:
```python
from yolort.models import yolov5n6
from yolort.runtime.ort_helper import export_onnx
onnx_path = "yolov5n6.onnx"
score_thresh = 0.35
model = yolov5n6(pretrained=True, score_thresh=score_thresh)
model = model.eval()
export_onnx(model=model, onnx_path=onnx_path)
```
=> Refactor ONNX export and tutorial

test/test_runtime_ort.py, tools/export_model.py, yolort/runtime/ort_helper.py
The `batch-size` argument / parameter is only used for models that include pre-processing. You need to specify the batch sizes and ensure that the number of input images is the same as the batches when inferring if you want to export multiple batches ONNX models.
=> Support multiple batches for exporting ONNX with pre-processing

deployment/tensorrt/main.cpp
=> Fix pre-processing in TensorRT C++ example

deployment/tensorrt/CMakeLists.txt, deployment/tensorrt/main.cpp
- Simplify function letterbox
- Support loading with TensorRT serialized model
=> Support loading with TensorRT SerializedModel

deployment/tensorrt/README.md, deployment/tensorrt/main.cpp, tools/export_model.py, yolort/runtime/trt_helper.py
=> Support exporting TensorRT serialized engine in CLI tools

README.md, deployment/onnxruntime/README.md, notebooks/export-onnx-inference-onnxruntime.ipynb, test/test_runtime_ort.py, yolort/data/__init__.py, yolort/data/_helper.py, yolort/runtime/y_onnxruntime.py, yolort/runtime/y_tensorrt.py
```python
from yolort.runtime import PredictorORT
onnx_path = 'yolov5n6.onnx'
device = 'cpu'
y_runtime = PredictorORT(onnx_path, device=device)
predictions = y_runtime.predict('bus.jpg')
```
=> Enhance `PredictorORT` to adapt to more scenarios

test/test_models.py, yolort/models/box_head.py, yolort/models/yolo_lite.py
The FPN implemented by TorchVision is a bit different from the PAN layers used by YOLOv5, it will result in 4 layers of output in head  with C3 (YOLOv5 only has 3 layers as a comparison), maybe we can rewrite the BackboneWithFPN in the future following the YOLOv5's PAN.
=> Use C3 following the model specification of YOLOv5

yolort/models/anchor_utils.py, yolort/models/box_head.py, yolort/utils/image_utils.py
Follow upstream https://github.com/pytorch/vision/pull/5331
=> Move bias initializations from private methods to constructors

yolort/utils/update_module_state.py
Seems that YOLOv5 will change the anchors setting when using the auto-anchor mechanism. So instead of attaching the `anchor_grids` via `checkpoint_yolov5.yaml["anchors"]`, we use the following formula to compute the `anchor_grids`:
```python
anchor_grids = (
(checkpoint_yolov5.model[-1].anchors * checkpoint_yolov5.model[-1].stride.view(-1, 1, 1))
.reshape(1, -1, 6)
.tolist()[0]
)
```
=> Fix `anchor_grids` for custom trained checkpoints

.github/workflows/ci-test.yml, requirements.txt, test/test_data_pipeline.py, test/test_models_yolov5.py, test/test_trainer.py, tools/eval_metric.py, yolort/data/__init__.py, yolort/models/_utils.py, yolort/models/darknet.py, yolort/models/darknetv4.py, yolort/models/darknetv6.py, yolort/models/path_aggregation_network.py, yolort/models/transformer.py, yolort/trainer/lightning_task.py
As mentioned in #219 , if someone just wants to use the models for inference, he/she doesn't need all additional features like:
- pytorch-lightning
- torchmetrics
=> Remove lightning dependencies

.github/workflows/ci-test.yml, README.md, setup.py, yolort/models/anchor_utils.py, yolort/utils/__init__.py, yolort/utils/dependency.py, yolort/v5/helper.py
- Compatibility updates for PyTorch 1.11.0
- Upgrade minimal version of PyTorch to 1.8.0
- Add Python 3.10 and remove Python 3.6
=> Add PyTorch 1.11.0 in GH Actions

deployment/libtorch/README.md, docs/requirements.txt, requirements.txt
In some circumstances, adding `TORCH_PATH` to the `LD_LIBRARY_PATH` environment variable will reduce some errors of finding CUDA.
=> Fix building docs and update docstrings

yolort/data/coco.py, yolort/data/coco_eval.py, yolort/relay/ir_visualizer.py, yolort/relay/trt_graphsurgeon.py, yolort/runtime/y_onnxruntime.py, yolort/runtime/y_tensorrt.py, yolort/utils/image_utils.py, yolort/utils/visualizer.py, yolort/v5/models/yolo.py, yolort/v5/utils/augmentations.py, yolort/v5/utils/general.py, yolort/v5/utils/plots.py, yolort/v5/utils/torch_utils.py
Builds on #366 to remove more `ImportError`s. Not sure if you wanted these done as well so I made it into an additional PR.
There are a few `ImportError`s remaining, it wasn't clear to me if I should remove those as well or keep them. I'll leave that to you to decide.
=> Improves more optional module imports

yolort/runtime/y_tensorrt.py
This is an update about to tensorrt python inference on windows:
import yolort before pytorch, this resolve issue in python inference on windows.
Close #390
=> Fix TensorRT Windows Python interface compatibility

tools/convert_txt_to_json.py, tools/convert_yolo_to_coco.py, yolort/utils/__init__.py, yolort/utils/annotations_converter.py, yolort/utils/yolo2coco.py
```sh
python3 tools/convert_txt_to_json.py --data_source data-bin/coco128/
--class_names notebooks/assets/coco.names
--label_dir labels
--image_dir images
```
=> Add CLI tool for converting YOLO-format to MSCOCO

yolort/relay/head_helper.py
Add export_type for onnxruntime and openvino.
Defaut is export onnxruntime. 
If use openvino, it will export a new onnx which will achieve real end to end.
=> Add `export_type` for exporting OpenVINO

tools/eval_metric.py, yolort/utils/logger.py
This PR aims to add basic [Weights and Biases](https://wandb.ai/site) Metric Logging by appending to the existing MetricLogger Class defined in [logger.py](https://github.com/zhiqwang/yolov5-rt-stack/blob/main/yolort/utils/logger.py) with minimal changes while supporting Multiple GPU logging with torch distributed.
The changes can be summarized as follows :-
* Pass the `args` to the `MetricLogger` which if the `--use_wandb` is set to `True`, creates and run and logs metrics using the `update` function.
* Add 3 extra arguments namely `--use_wandb`, `--wandb_project` and `--wandb_entity` which can be used to specify whether to use wandb, the name of the project to be used ("yolov5-rt" by default) and name of the entity to be used.
=> Add Weights and Biases to `MetricLogger` Class

yolort/relay/trt_graphsurgeon.py, yolort/relay/trt_inference.py, yolort/runtime/trt_helper.py
I have tested yolov5s and yolov6s onnx.
Now `export_tensorrt_engine` api support onnx input which is exported by yolov5 / yolov6 original repo onnx export.
=> Support ONNX exported from YOLOv5 and YOLOv6

yolort/models/_utils.py, yolort/models/transform.py
These changes made it possible for me to use _save_for_lite_interpreter
- Lite interpreter bytecode can't handle `with `
- Lite interpreter doesn't handle normal python classes
=> Support exporting to PyTorch mobile interpreter

yolort/v5/utils/plots.py
Fix #467 Remove Matplotlib agg backend. See https://stackoverflow.com/questions/56656777/userwarning-matplotlib-is-currently-using-agg-which-is-a-non-gui-backend-so for more details.
=> Remove Matplotlib agg backend

yolort/relay/trt_graphsurgeon.py
This PR resolves #508 . The fix ensures that the exported models now correctly retain the specified batch size as intended, providing improved flexibility for users working with ONNX models.
=> Resolved Issue: Fix Exporting ONNX Model with Fixed Batch Size of 1 Using export_tensorrt_engine
